import Link from "next/link";
import { TopNav } from "../_components/top-nav";
import { SiteFooter } from "../_components/site-footer";

/**
 * Checkout page — Tier Ascension Checkout.
 *
 * Source: docs/prototype.html (CheckoutPage component).
 * Centered two-column tier comparison: Core AI Synthesis (acrylic
 * glass) vs Hybrid Specialist Review (premium dark card with
 * ochre accent).
 *
 * Reads `?trip=<id>` from the URL (set by the trip page's
 * "Unlock Trip" CTA). When the param is present, the two CTAs
 * are functional forms:
 *   - "Continue with Core AI" → just navigates to the trip page
 *     (the trip stays in its current draft/paid state; no
 *     payment is required for the Core AI tier).
 *   - "Upgrade & Finalize" → POSTs to the existing
 *     /api/trips/[tripId]/unlock API, which creates a Stripe
 *     (or fake) checkout session and redirects.
 * When the param is missing (the page is opened directly from
 * the marketing surface), the CTAs fall back to /account +
 * /planner so the page is never a dead end.
 */
export default async function CheckoutPage({
  searchParams
}: {
  searchParams: Promise<{ trip?: string }>;
}) {
  const { trip: tripParam } = await searchParams;
  const tripId = tripParam?.trim() || null;
  const tripHref = tripId ? `/trip/${tripId}` : "/account";

  return (
    <>
      <TopNav />
      <div className="pt-header-height min-h-screen flex flex-col font-body-md text-body-md text-on-surface">
        <main
          id="main-content"
          className="flex-grow pt-32 pb-24 px-container-padding-sm md:px-container-padding-lg max-w-7xl mx-auto w-full flex flex-col justify-center items-center"
          style={{
            backgroundImage:
              "radial-gradient(var(--color-grid-pattern) 1px, transparent 1px)",
            backgroundSize: "24px 24px",
          }}
        >
          <div className="text-center mb-16 max-w-2xl mx-auto">
            <h1 className="font-display-mobile md:font-display text-display-mobile md:text-display text-primary mb-6">
              Elevate Your Itinerary
            </h1>
            <p className="font-headline-sm text-headline-sm text-on-surface-variant">
              Choose the level of expertise required to finalize your journey.
              Our Core AI provides exceptional foundational planning, while our
              Hybrid Specialist Review adds the irreplaceable touch of human
              intuition.
            </p>
            {tripId ? (
              <p className="font-mono-micro text-mono-micro uppercase tracking-widest text-on-surface-variant/70 mt-4">
                for trip #{tripId}
              </p>
            ) : null}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-section-gap w-full max-w-5xl mx-auto relative z-10">
            {/* Tier 1: Core AI (Included) */}
            <div className="acrylic-glass rounded-xl p-8 flex flex-col h-full relative group hover:shadow-lg transition-shadow duration-300">
              <h2 className="font-headline-lg text-headline-lg text-primary mb-2">
                Core AI Synthesis
              </h2>
              <p className="font-body-md text-body-md text-on-surface-variant mb-6">
                A complete, structured itinerary generated by our spatial
                engine. Maps, pacing, and curated routes — no human in the
                loop.
              </p>
              <ul className="font-body-md text-body-md text-on-surface space-y-2 mb-6">
                <li className="flex items-start gap-2">
                  <span className="material-symbols-outlined text-olive-light text-[18px] mt-0.5">check_circle</span>
                  Structured day-by-day route
                </li>
                <li className="flex items-start gap-2">
                  <span className="material-symbols-outlined text-olive-light text-[18px] mt-0.5">check_circle</span>
                  Map + filmstrip stops with opening hours
                </li>
                <li className="flex items-start gap-2">
                  <span className="material-symbols-outlined text-olive-light text-[18px] mt-0.5">check_circle</span>
                  Vault + exports (PDF, mobile)
                </li>
              </ul>
              <div className="pt-6 border-t border-primary/10 mt-auto">
                <div className="flex justify-between items-center mb-6">
                  <span className="font-label-ui text-label-ui text-on-surface-variant">
                    Total Cost
                  </span>
                  <span className="font-headline-sm text-headline-sm text-primary">
                    Included
                  </span>
                </div>
                <Link
                  href={tripHref}
                  data-testid="checkout-continue-core"
                  className="block text-center w-full py-4 px-6 rounded-lg border border-outline text-primary font-label-ui text-label-ui hover:bg-surface-variant transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ochre-light focus-visible:ring-offset-2"
                >
                  Continue with Core AI
                </Link>
              </div>
            </div>

            {/* Tier 2: Hybrid Specialist Review */}
            <div className="rounded-xl p-8 flex flex-col h-full relative group bg-olive-dark text-linen-dark border border-ochre-light/50 shadow-[0_24px_64px_rgba(29,42,35,0.25)] hover:shadow-[0_32px_80px_rgba(206,147,63,0.18)] transition-shadow duration-300">
              <div className="absolute -top-3 right-6 bg-ochre-light text-olive-dark font-mono-micro text-mono-micro uppercase tracking-widest px-3 py-1 rounded-full shadow-md">
                Recommended
              </div>
              <div className="absolute top-0 right-0 w-48 h-48 bg-ochre-light/10 blur-3xl rounded-full pointer-events-none -z-10" />
              <h2 className="font-headline-lg text-headline-lg text-linen-dark mb-2">
                Hybrid Specialist Review
              </h2>
              <p className="font-body-md text-body-md text-linen-dark/80 mb-6">
                Our destination specialists audit, refine, and personalize
                your itinerary. The irreplaceable touch of human intuition.
              </p>
              <ul className="font-body-md text-body-md text-linen-dark/90 space-y-2 mb-6">
                <li className="flex items-start gap-2">
                  <span
                    className="material-symbols-outlined text-ochre-light text-[18px] mt-0.5"
                    style={{ fontVariationSettings: "'FILL' 1" }}
                  >
                    verified_user
                  </span>
                  Specialist audit of every stop
                </li>
                <li className="flex items-start gap-2">
                  <span
                    className="material-symbols-outlined text-ochre-light text-[18px] mt-0.5"
                    style={{ fontVariationSettings: "'FILL' 1" }}
                  >
                    stars
                  </span>
                  Personalized recommendations
                </li>
                <li className="flex items-start gap-2">
                  <span
                    className="material-symbols-outlined text-ochre-light text-[18px] mt-0.5"
                    style={{ fontVariationSettings: "'FILL' 1" }}
                  >
                    forum
                  </span>
                  Async chat with your specialist
                </li>
                <li className="flex items-start gap-2">
                  <span
                    className="material-symbols-outlined text-ochre-light text-[18px] mt-0.5"
                    style={{ fontVariationSettings: "'FILL' 1" }}
                  >
                    schedule
                  </span>
                  48-hour turnaround
                </li>
              </ul>
              <div className="pt-6 border-t border-white/10 mt-auto">
                <div className="flex justify-between items-center mb-6">
                  <span className="font-label-ui text-label-ui text-linen-dark/80">
                    One-time Ascension Fee
                  </span>
                  <span className="font-headline-lg text-headline-lg text-ochre-light">
                    €65
                  </span>
                </div>
                {tripId ? (
                  <form
                    action={`/api/trips/${tripId}/unlock`}
                    method="post"
                    className="block"
                  >
                    <button
                      type="submit"
                      data-testid="checkout-upgrade-finalize"
                      className="block text-center w-full py-4 px-6 rounded-lg bg-ochre-dark text-on-primary font-label-ui text-label-ui hover:bg-ochre-light hover:text-on-secondary-container transition-colors duration-200 shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ochre-light focus-visible:ring-offset-2"
                    >
                      Upgrade &amp; Finalize
                    </button>
                  </form>
                ) : (
                  <Link
                    href="/planner"
                    data-testid="checkout-upgrade-finalize"
                    className="block text-center w-full py-4 px-6 rounded-lg bg-ochre-dark text-on-primary font-label-ui text-label-ui hover:bg-ochre-light hover:text-on-secondary-container transition-colors duration-200 shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ochre-light focus-visible:ring-offset-2"
                  >
                    Start a trip to unlock
                  </Link>
                )}
              </div>
            </div>
          </div>

          {!tripId ? (
            <p className="text-center mt-8 font-body-md text-body-md text-on-surface-variant max-w-prose">
              <span className="material-symbols-outlined align-middle text-[18px] mr-1">
                info
              </span>
              These tiers apply to a specific trip. Plan one first and the
              checkout options will land here automatically.
            </p>
          ) : null}
        </main>
        <SiteFooter />
      </div>
    </>
  );
}
