create table if not exists public.partners (
  id text primary key,
  name text not null,
  type text not null default '',
  coverage_regions text[] not null default '{}',
  status text not null default 'Draft',
  notes text not null default '',
  link text not null default '',
  is_affiliate boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reviewer_assignments (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  reviewer_id text not null references public.reviewers(id) on delete cascade,
  status text not null default 'assigned',
  notes text not null default '',
  created_at timestamptz not null default now(),
  completed_at timestamptz null,
  updated_at timestamptz not null default now()
);

alter table public.partners enable row level security;
alter table public.reviewer_assignments enable row level security;

grant select, insert, update, delete on public.partners to service_role;
grant select, insert, update, delete on public.reviewer_assignments to service_role;
grant usage, select on all sequences in schema public to service_role;
