-- Durable export job state for PDF, calendar, and markdown generation.
-- Apply after the ownership/RLS foundation migrations.

create table if not exists public.trip_export_jobs (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  owner_user_id uuid not null,
  format text not null check (format in ('markdown', 'pdf', 'calendar')),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'ready', 'error', 'retry')),
  attempts integer not null default 0 check (attempts >= 0),
  error_code text null,
  error_message text null,
  requested_at timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null,
  updated_at timestamptz not null default now(),
  unique (trip_id, format)
);

create index if not exists trip_export_jobs_owner_status_idx
  on public.trip_export_jobs(owner_user_id, status, updated_at desc);

create index if not exists trip_export_jobs_trip_idx
  on public.trip_export_jobs(trip_id, updated_at desc);

alter table public.trip_export_jobs enable row level security;

grant select on public.trip_export_jobs to authenticated;
grant select, insert, update, delete on public.trip_export_jobs to service_role;
grant usage, select on sequence public.trip_export_jobs_id_seq to service_role;

drop policy if exists "trip_export_jobs_traveler_owner_select" on public.trip_export_jobs;
create policy "trip_export_jobs_traveler_owner_select"
on public.trip_export_jobs
for select
to authenticated
using (
  owner_user_id = (select auth.uid())
  and (select private.current_app_role()) = 'traveler'
);

drop policy if exists "trip_export_jobs_traveler_owner_insert" on public.trip_export_jobs;
create policy "trip_export_jobs_traveler_owner_insert"
on public.trip_export_jobs
for insert
to authenticated
with check (
  owner_user_id = (select auth.uid())
  and (select private.current_app_role()) = 'traveler'
);

drop policy if exists "trip_export_jobs_traveler_owner_update" on public.trip_export_jobs;
create policy "trip_export_jobs_traveler_owner_update"
on public.trip_export_jobs
for update
to authenticated
using (
  owner_user_id = (select auth.uid())
  and (select private.current_app_role()) = 'traveler'
)
with check (
  owner_user_id = (select auth.uid())
  and (select private.current_app_role()) = 'traveler'
);
