create table if not exists public.booking_clicks (
  id bigint generated by default as identity primary key,
  partner_id text not null references public.partners(id) on delete cascade,
  trip_id bigint null references public.trips(id) on delete set null,
  source text not null,
  target text not null,
  referer text null,
  user_agent text null,
  created_at timestamptz not null default now()
);

alter table public.booking_clicks enable row level security;

grant select, insert, update, delete on public.booking_clicks to service_role;
grant usage, select on all sequences in schema public to service_role;
