create table if not exists public.trip_briefs (
  id bigint generated by default as identity primary key,
  destination_country text not null,
  destination_regions text[] not null default '{}',
  start_date date null,
  end_date date null,
  trip_length_days integer not null,
  travelers_count integer not null,
  traveler_type text not null,
  budget_level text not null,
  pace text not null,
  interests text[] not null default '{}',
  food_preferences text[] not null default '{}',
  avoidances text[] not null default '{}',
  transport_mode text not null,
  accommodation_location text not null default '',
  raw_input text not null,
  normalized_json jsonb not null,
  status text not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  trip_brief_id bigint not null references public.trip_briefs(id) on delete cascade,
  country_slug text not null,
  title text not null,
  status text not null default 'draft',
  visibility text not null default 'private',
  is_paid boolean not null default false,
  has_human_review boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trip_briefs enable row level security;
alter table public.trips enable row level security;

grant select, insert, update, delete on public.trip_briefs to service_role;
grant select, insert, update, delete on public.trips to service_role;
grant usage, select on all sequences in schema public to service_role;
